package com.selenium.firstprogram;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

/*This program is to access elements of login page of Salesforce using Xpath and css Selectors.
 * Here the xpath and css are auto generated by browsers.*/

public class LoginSalesforceAutomation {
	public static void main(String[] args) {

		// Invoking the .exe file for the browser.
		System.setProperty("webdriver.chrome.driver",
				"E:\\Techademy Assignments\\SeleniumJar\\chromedriver_win32\\chromedriver.exe");

		// Creating the object of web driver.
		WebDriver driver = new ChromeDriver();

		// Url for browser.
		driver.get("https://login.salesforce.com");

		// By Xpath
		driver.findElement(By.xpath("//*[@id='username']")).sendKeys("qwerty");
		driver.findElement(By.xpath("//*[@id='password']")).sendKeys("0123456789");
		driver.findElement(By.xpath("//*[@id='Login']")).click();

		/*
		 * //*[@id='username']
		 * 
		 * //*[@id='password']
		 * 
		 * //*[@id='Login']
		 */

		// To get CSS Selector Use Firefox in chrome Unable to copy which are auto
		// generated by browser.
		
		//To display the error message:
		System.out.println(driver.findElement(By.xpath("//*[@id=\'error\']")).getText());
	}
}
